language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

cache:
  directories:
    - $HOME/.m2

script:
- "mvn clean verify -f ./org.birenheide.bf.parent -B -Pintegration-tests"
